# Generated by Django 5.2.5 on 2025-09-02 19:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(default=0)),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cns', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_do_pai', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_da_mae', models.CharField(blank=True, max_length=200, null=True)),
                ('celular1', models.CharField(blank=True, max_length=20, null=True)),
                ('celular2', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=15, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
                ('data_ultima_consulta', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
    ]
