# Generated by Django 5.2.5 on 2025-09-02 19:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_consulta', models.CharField(choices=[('NEUROCIRURGIAO', 'Neurocirurgião'), ('ORTOPEDISTA', 'Ortopedista'), ('CLINICO_GERAL', 'Clínico Geral'), ('PEDIATRA', 'Pediatra'), ('GINECOLOGISTA', 'Ginecologista'), ('OFTALMOLOGISTA', 'Oftalmologista'), ('OTORRINOLARINGOLOGISTA', 'Otorrinolaringologista'), ('UROLOGISTA', 'Urologista'), ('CARDIOLOGISTA', 'Cardiologista')], max_length=50)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGENDADA', 'Agendada'), ('REAGENDADA', 'Reagendada'), ('REALIZADA', 'Realizada'), ('URGENTE', 'Urgente'), ('IMEDIATA', 'Imediata'), ('CANCELADA', 'Cancelada'), ('NAO_COMPARECEU', 'Não Compareceu')], max_length=20)),
                ('data_solicitacao', models.DateField(default=django.utils.timezone.now)),
                ('data_agendamento', models.DateField(blank=True, null=True)),
                ('estabelecimento', models.CharField(blank=True, choices=[('POLICLINICA', 'Policlínica'), ('SARAH', 'Sarah'), ('REDE_MUNICIPAL', 'Rede Municipal')], max_length=50, null=True)),
                ('observacao', models.TextField(blank=True, max_length=1000, null=True)),
                ('motivo', models.CharField(blank=True, max_length=500, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'consultas',
            },
        ),
    ]
